# Generated by Django 5.2.17 on 2026-09-14 19:38

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(unique=True)),
                ('usd_brl', models.DecimalField(decimal_places=8, max_digits=20)),
            ],
            options={
                'verbose_name': 'cotação USD/BRL',
                'verbose_name_plural': 'cotações USD/BRL',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='Fundo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('caixa_inicial', models.DecimalField(decimal_places=2, default=Decimal('100000000.00'), max_digits=20)),
                ('cotas_emitidas', models.DecimalField(decimal_places=2, default=Decimal('1000000.00'), max_digits=20)),
                ('inicio', models.DateField(help_text='Primeiro dia de rentabilidade do fundo.')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'fundos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TaxaCDI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(unique=True)),
                ('taxa_diaria', models.DecimalField(decimal_places=10, max_digits=12)),
            ],
            options={
                'verbose_name': 'taxa CDI',
                'verbose_name_plural': 'taxas CDI',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='Ordem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=20)),
                ('quantidade', models.PositiveIntegerField()),
                ('direcao', models.CharField(choices=[('COMPRA', 'Compra'), ('VENDA', 'Venda')], max_length=10)),
                ('enviada_em', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EXECUTADA', 'Executada'), ('REJEITADA', 'Rejeitada')], default='PENDENTE', max_length=10)),
                ('motivo_rejeicao', models.TextField(blank=True)),
                ('enviada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('fundo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens', to='desafio.fundo')),
            ],
            options={
                'ordering': ['enviada_em'],
            },
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nucleo', models.CharField(choices=[('MACRO', 'Macro & Data Science'), ('RISCO', 'Risco & Backoffice'), ('EQUITY', 'Equity Research')], max_length=40)),
                ('fundo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='membros', to='desafio.fundo')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='participante', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrecoFechamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=20)),
                ('data', models.DateField()),
                ('preco', models.DecimalField(decimal_places=8, max_digits=20)),
            ],
            options={
                'verbose_name': 'preço de fechamento',
                'verbose_name_plural': 'preços de fechamento',
                'ordering': ['-data', 'ticker'],
                'unique_together': {('ticker', 'data')},
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=20)),
                ('quantidade', models.BigIntegerField()),
                ('preco_nativo', models.DecimalField(decimal_places=8, max_digits=20)),
                ('cambio', models.DecimalField(decimal_places=8, default=Decimal('1'), max_digits=20)),
                ('executado_em', models.DateField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('fundo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trades', to='desafio.fundo')),
                ('ordem', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trade', to='desafio.ordem')),
            ],
            options={
                'ordering': ['executado_em', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Fechamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('caixa', models.DecimalField(decimal_places=2, max_digits=20)),
                ('valor_posicoes', models.DecimalField(decimal_places=2, max_digits=20)),
                ('patrimonio', models.DecimalField(decimal_places=2, max_digits=20)),
                ('cota', models.DecimalField(decimal_places=2, max_digits=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('fundo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fechamentos', to='desafio.fundo')),
            ],
            options={
                'ordering': ['-data', 'fundo'],
                'unique_together': {('fundo', 'data')},
            },
        ),
        migrations.CreateModel(
            name='Lancamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ALUGUEL_SHORT', 'Aluguel de short'), ('AJUSTE', 'Ajuste da mesa')], max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, help_text='Negativo debita o caixa.', max_digits=20)),
                ('executado_em', models.DateField()),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('fundo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos', to='desafio.fundo')),
            ],
            options={
                'ordering': ['executado_em', 'id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('tipo', 'ALUGUEL_SHORT')), fields=('fundo', 'executado_em'), name='aluguel_unico_por_dia')],
            },
        ),
    ]
